version: "3.7"

services:
  wdb:
    image: kozea/wdb:3.3.0
    ports: ["1984:1984"]
    networks:
      - odoonet
    depends_on: ["db"]

  # ------------------------

  odoo:
    # Uncomment the next lines to build the image. This is mainly useful
    # when you need to add additional requirements on the building phase
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    volumes:
      # Host paths (.vscode configuration)
      - ./.devcontainer/.vscode:/etc/.vscode
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ~/.ssh/:/opt/odoo/.ssh/
    environment:
      - LOG_LEVEL=debug
      - WITHOUT_DEMO=False
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_WEB_PORT=1984
    depends_on: ["db", "wdb"]
    command: ["odoo", "--dev", "wdb,reload,qweb,werkzeug,xml"]
