version: "3.7"

services:
  wdb:
    image: kozea/wdb:3.3.0
    ports: ["1984:1984"]
    networks:
      - odoonet
    depends_on: ["db"]

  # ------------------------

  odoo:
    # Uncomment the next lines to build the image. This is mainly useful
    # when you need to add additional requirements on the building phase
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      # Host paths (odoo src code & .vscode conf)
      - ./src/odoo:/${ODOO_BASEPATH}
      - ./config:/etc/odoo:ro
      - ./.devcontainer/.vscode:/etc/.vscode
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_WEB_PORT=1984
    command: ["odoo", "--dev", "wdb,reload,qweb,werkzeug,xml"]
    depends_on: ["db", "wdb"]
