version: '3.4'

x-odoo:
  &default-odoo
  tty: true
  image: odoo:${ODOO_VERSION}
  build:
    context: .
    # Variables  defined in the .env file, to be used at build time
    args:
      # Odoo's default configurations
      ODOO_USER: ${ODOO_USER}
      ODOO_BASEPATH: ${ODOO_BASEPATH}
      ODOO_CONF: ${ODOO_CONF}
      ODOO_CMD: ${ODOO_CMD}
      APP_UID: ${APP_UID}
      APP_GID: ${APP_GID}
      # Libraries version
      ODOO_VERSION: ${ODOO_VERSION}
      PSQL_VERSION: ${PSQL_VERSION}
      WKHTMLTOX_VERSION: ${WKHTMLTOX_VERSION}
      WKHTMLTOPDF_CHECKSUM: ${WKHTMLTOPDF_CHECKSUM}
      NODE_VERSION: ${NODE_VERSION}
      BOOTSTRAP_VERSION: ${BOOTSTRAP_VERSION}

  environment:
    ODOO_CMD: ${ODOO_CMD}  # odoo-bin to be used in the entrypoint

  ports: ['8069:8069', '8072:8072', '3000:3000']

  volumes:
    # Named volumes
    - odoo-data:${ODOO_DATA_DIR}
    - odoo-testlogs:/var/log/odoo
    # Host path (conf)
    - ./config:/etc/odoo/:ro
    # Host paths (source)
    - ./vendor/odoo/ce:${ODOO_BASEPATH}
    - ./vendor/odoo/ce/odoo:${ODOO_FRM}:ro
    - ./vendor/odoo/ce/addons:${ODOO_ADDONS_BASEPATH}/000:ro
    - ./vendor/odoo/ee:${ODOO_ADDONS_BASEPATH}/001:ro
    - ./extra_addons:/mnt/extra-addons:ro
  depends_on:
    - postgres
  networks:
    - odoonet

networks:
  odoonet:

volumes:
  db_data: {driver: local}
  odoo-data: {driver: local}
  odoo-testlogs: {driver: local}
  psql: {driver: local}

services:

# ------------------------

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']
    networks:
      - odoonet

# ------------------------

  postgres:
    image: postgres:${PSQL_VERSION}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      odoonet:
        aliases:
          - db

# ------------------------

  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    # TODO: add a variable to allow a dynamic ADDONS_PATH
    command: ['odoo']
    depends_on: ['postgres']

# ========================

  dev:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['postgres', 'wdb']

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    # TODO: logfile shouldn't be hardcoded
    command: ['odoo', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '/var/log/odoo/odoo-server.log']

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', 'shell']
