version: "3.7"

networks:
  default:
    external:
      name: cloudbuild
  odoonet:

volumes:
  odoo-data:
  odoo-testlogs:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:${ODOO_VERSION}
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (addons & conf)
      - ./custom:${ODOO_EXTRA_ADDONS}
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}

    depends_on:
      - db

    networks:
      odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      odoonet:
