version: '3.4'

x-odoo:
  &default-odoo
  tty: true
  image: odoo:${ODOO_VERSION}
  build:
    context: .
    target: ${INSTALL_TYPE:-bridged}
    # Variables  defined in the .env file, to be used at build time
    args:
      # Odoo's default configurations
      ODOO_USER: ${ODOO_USER}
      ODOO_BASEPATH: ${ODOO_BASEPATH}
      ODOO_ADDONS_BASEPATH: ${ODOO_ADDONS_BASEPATH}
      ODOO_EXTRA_ADDONS: ${ODOO_EXTRA_ADDONS}
      ODOO_DATA_DIR: ${ODOO_DATA_DIR}
      ODOO_LOGS_DIR: ${ODOO_LOGS_DIR}
      ODOO_RC: ${ODOO_RC}
      ODOO_CMD: ${ODOO_CMD}
      APP_UID: ${APP_UID}
      APP_GID: ${APP_GID}
      # Libraries version
      ODOO_VERSION: ${ODOO_VERSION}
      PSQL_VERSION: ${PSQL_VERSION}
      WKHTMLTOX_VERSION: ${WKHTMLTOX_VERSION}
      WKHTMLTOPDF_CHECKSUM: ${WKHTMLTOPDF_CHECKSUM}
      NODE_VERSION: ${NODE_VERSION}
      BOOTSTRAP_VERSION: ${BOOTSTRAP_VERSION}

  environment:
    ODOO_CMD: ${ODOO_CMD}  # odoo-bin to be used in the entrypoint

  ports: ['8069:8069', '8072:8072', '3000:3000']

  volumes:
    # Named volumes
    - odoo-data:${ODOO_DATA_DIR}
    - odoo-testlogs:${ODOO_LOGS_DIR}
    # Host path (conf)
    - ./config:/etc/odoo/:ro
    # Host paths (source)
    - ./src/odoo/ee:${ODOO_ADDONS_BASEPATH}/001:ro
    - ./custom_addons:${ODOO_EXTRA_ADDONS}
  depends_on:
    - postgres
  networks:
    - odoonet

networks:
  odoonet:

volumes:
  db_data: {driver: local}
  odoo-data: {driver: local}
  odoo-testlogs: {driver: local}
  psql: {driver: local}

services:

# ========================

  filebrowser:
    image: filebrowser/filebrowser
    ports: ['8080:80']
    command: ['--noauth']
    volumes:
      - odoo-data:/srv/data
      - odoo-testlogs:/srv/testlogs

# ========================

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']
    networks:
      - odoonet

# ------------------------

  postgres:
    image: postgres:${PSQL_VERSION}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      odoonet:
        aliases:
          - db

# ========================

  dev:
    << : *default-odoo
    command: ['odoo', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['postgres', 'wdb']
    volumes:
      - ./src/odoo/ce:${ODOO_BASEPATH}:ro

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    command: ['odoo', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '${ODOO_LOGS_DIR}/odoo-server.log']
    volumes:
      - ./src/odoo/ce:${ODOO_BASEPATH}:ro

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    command: ['odoo', 'shell']
