version: '3.4'

x-odoo:
  &default-odoo
  tty: true
  image: odoo:${ODOO_VERSION}
  build:
    context: .
    args:
      ODOO_VERSION: ${ODOO_VERSION}
      PSQL_VERSION: 10
      WKHTMLTOX_VERSION: 0.12.5
      WKHTMLTOPDF_CHECKSUM: 1140b0ab02aa6e17346af2f14ed0de807376de475ba90e1db3975f112fbd20bb
      NODE_VERSION: 6
      BOOTSTRAP_VERSION: 3.3.7
      ODOO_USER: ${ODOO_USER}
      ODOO_HOME: ${ODOO_HOME}
      ODOO_BASEPATH: ${ODOO_BASEPATH}
      ODOO_RC: ${ODOO_RC}
      ODOO_CMD: ${ODOO_CMD}
      ODOO_FRM: ${ODOO_FRM}
      ODOO_ADDONS_BASEPATH: ${ODOO_ADDONS_BASEPATH}
      ODOO_DATA_DIR: ${ODOO_DATA_DIR}
      APP_UID: ${APP_UID}
      APP_GID: ${APP_GID}
  ports: ['8069:8069', '8072:8072', '3000:3000']
  volumes:
    # Named volumes
    - odoo-data:/var/lib/odoo
    - odoo-testlogs:/var/log/odoo
    # Host path (conf)
    - ./config:/etc/odoo:ro
    # Host paths (source)
    - ./vendor/odoo/ce:/opt/odoo
    - ./vendor/odoo/ce/odoo:/opt/odoo/odoo:ro
    - ./vendor/odoo/ce/addons:/opt/odoo/addons/000:ro
    - ./vendor/odoo/ee:/opt/odoo/addons/001:ro
    - ./extra_addons:/mnt/extra-addons:ro
  depends_on:
    - postgres
  networks:
    - odoonet

networks:
  odoonet:

volumes:
  db_data: {driver: local}
  odoo-data: {driver: local}
  odoo-testlogs: {driver: local}
  psql: {driver: local}

services:

# ------------------------

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']
    networks:
      - odoonet

# ------------------------

  postgres:
    image: postgres:10
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
        # TODO: this variables shouldn't be hardcoded
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      odoonet:
        aliases:
          - db

# ------------------------

  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    # TODO: add a variable to allow a dynamic ADDONS_PATH
    command: ['odoo']
    depends_on: ['postgres']

# ========================

  dev:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['postgres', 'wdb']

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    # TODO: logfile shouldn't be hardcoded
    command: ['odoo', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '/var/log/odoo/odoo-server.log']

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', 'shell']
