name: Publish Dockerdoo

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/workflows/**"
      - "**/resources/**"
      - Dockerfile
  pull_request:
    paths:
      - "**/workflows/**"
      - "**/resources/**"
      - Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - odoo_version: 14.0
            python_version: 3.10
            python_variant: slim-buster
            wkhtmltox_version: 0.12.5

          - odoo_version: 15.0
            python_version: 3.10
            python_variant: slim-bullseye
            wkhtmltox_version: 0.12.6

          - odoo_version: 16.0
            python_version: 3.12
            python_variant: slim-bullseye
            wkhtmltox_version: 0.12.6

          - odoo_version: 17.0
            python_version: 3.13
            python_variant: slim-bullseye
            wkhtmltox_version: 0.12.6

          - odoo_version: master
            python_version: 3.13
            python_variant: slim-bullseye
            wkhtmltox_version: 0.12.6
    uses: ./.github/workflows/build-docker-image.yml
    with:
      odoo_version: ${{ matrix.odoo_version }}
      python_version: ${{ matrix.python_version }}
      python_variant: ${{ matrix.python_variant }}
      wkhtmltox_version: ${{ matrix.wkhtmltox_version }}
      platform: ${{ matrix.platform }}
      dockerfile_path: Dockerfile
      dockerfile_target: production
      app_name: dockerdoo
    secrets: inherit
  test:
    needs: [build]
    uses: ./.github/workflows/unit-tests.yml
    with:
      image: ghcr.io/iterativo-git/dockerdoo@${{ needs.build.outputs.image_digest }}
    secrets: inherit
  push:
    needs: [build, test]
    uses: ./.github/workflows/build-docker-image.yml
    if: ${{ github.event_name != 'pull_request' }}
    with:
      image: ghcr.io/iterativo-git/dockerdoo@${{ needs.build.outputs.image_digest }}
    secrets: inherit
